//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace import
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufactur_
    {
        public int ID { get; set; }
        public string manufactr { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
    }
}
