//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace import
{
    using System;
    using System.Collections.Generic;
    
    public partial class productImport_
    {
        public int ID { get; set; }
        public string Product { get; set; }
        public string Image { get; set; }
        public string Manufacter { get; set; }
        public string Active { get; set; }
        public Nullable<double> Cost { get; set; }
    }
}
